// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/friend.proto

package friend

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendRequest) Reset() {
	*x = AddFriendRequest{}
	mi := &file_proto_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequest) ProtoMessage() {}

func (x *AddFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequest.ProtoReflect.Descriptor instead.
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friend_proto_rawDescGZIP(), []int{0}
}

func (x *AddFriendRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AddFriendRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type AddFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResponse) Reset() {
	*x = AddFriendResponse{}
	mi := &file_proto_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResponse) ProtoMessage() {}

func (x *AddFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResponse.ProtoReflect.Descriptor instead.
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friend_proto_rawDescGZIP(), []int{1}
}

func (x *AddFriendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MutualFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualFriendsRequest) Reset() {
	*x = MutualFriendsRequest{}
	mi := &file_proto_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualFriendsRequest) ProtoMessage() {}

func (x *MutualFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualFriendsRequest.ProtoReflect.Descriptor instead.
func (*MutualFriendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_friend_proto_rawDescGZIP(), []int{2}
}

func (x *MutualFriendsRequest) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *MutualFriendsRequest) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type MutualFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MutualFriends []string               `protobuf:"bytes,1,rep,name=mutual_friends,json=mutualFriends,proto3" json:"mutual_friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualFriendsResponse) Reset() {
	*x = MutualFriendsResponse{}
	mi := &file_proto_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualFriendsResponse) ProtoMessage() {}

func (x *MutualFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualFriendsResponse.ProtoReflect.Descriptor instead.
func (*MutualFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_friend_proto_rawDescGZIP(), []int{3}
}

func (x *MutualFriendsResponse) GetMutualFriends() []string {
	if x != nil {
		return x.MutualFriends
	}
	return nil
}

var File_proto_friend_proto protoreflect.FileDescriptor

const file_proto_friend_proto_rawDesc = "" +
	"\n" +
	"\x12proto/friend.proto\x12\x06friend\x1a\x1cgoogle/api/annotations.proto\"6\n" +
	"\x10AddFriendRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"-\n" +
	"\x11AddFriendResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\x14MutualFriendsRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\">\n" +
	"\x15MutualFriendsResponse\x12%\n" +
	"\x0emutual_friends\x18\x01 \x03(\tR\rmutualFriends2\xf7\x01\n" +
	"\rFriendService\x12X\n" +
	"\tAddFriend\x12\x18.friend.AddFriendRequest\x1a\x19.friend.AddFriendResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/add-friend\x12\x8b\x01\n" +
	"\x10GetMutualFriends\x12\x1c.friend.MutualFriendsRequest\x1a\x1d.friend.MutualFriendsResponse\":\x82\xd3\xe4\x93\x024Z!\x12\x1f/mutual-friends/{user1}/{user2}\x12\x0f/mutual-friendsB\x16Z\x14friends/proto;friendb\x06proto3"

var (
	file_proto_friend_proto_rawDescOnce sync.Once
	file_proto_friend_proto_rawDescData []byte
)

func file_proto_friend_proto_rawDescGZIP() []byte {
	file_proto_friend_proto_rawDescOnce.Do(func() {
		file_proto_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friend_proto_rawDesc), len(file_proto_friend_proto_rawDesc)))
	})
	return file_proto_friend_proto_rawDescData
}

var file_proto_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_friend_proto_goTypes = []any{
	(*AddFriendRequest)(nil),      // 0: friend.AddFriendRequest
	(*AddFriendResponse)(nil),     // 1: friend.AddFriendResponse
	(*MutualFriendsRequest)(nil),  // 2: friend.MutualFriendsRequest
	(*MutualFriendsResponse)(nil), // 3: friend.MutualFriendsResponse
}
var file_proto_friend_proto_depIdxs = []int32{
	0, // 0: friend.FriendService.AddFriend:input_type -> friend.AddFriendRequest
	2, // 1: friend.FriendService.GetMutualFriends:input_type -> friend.MutualFriendsRequest
	1, // 2: friend.FriendService.AddFriend:output_type -> friend.AddFriendResponse
	3, // 3: friend.FriendService.GetMutualFriends:output_type -> friend.MutualFriendsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_friend_proto_init() }
func file_proto_friend_proto_init() {
	if File_proto_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friend_proto_rawDesc), len(file_proto_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friend_proto_goTypes,
		DependencyIndexes: file_proto_friend_proto_depIdxs,
		MessageInfos:      file_proto_friend_proto_msgTypes,
	}.Build()
	File_proto_friend_proto = out.File
	file_proto_friend_proto_goTypes = nil
	file_proto_friend_proto_depIdxs = nil
}
